### PR TITLE
[BUG] Disable Checkbox

### LINKED ISSUE #27: 15. Bug: Como usuario, quiero marcar un artículo de mi lista de la compra como comprado para que la aplicación pueda saber con qué frecuencia compro diferentes artículos.
Bug 🐞 :
Sucede cuando tienes un producto marcado como "comprado" (checkbox como `checked` ✔️ ), como usuario tienes todavía la posibilidad de "volver a marcar como comprado" un producto, sin importar si ya paso al menos un día y esto impacta/actualiza la base de datos. Lo cual no es un comportamiento esperado. Incluso, si realizas un check la primera vez, genera un error relacionado al input & custom input. (ver videos)

Related issues: #8

https://user-images.githubusercontent.com/8689897/140624544-f039e2df-48c0-4294-b374-c8a20d875151.mp4

https://user-images.githubusercontent.com/8689897/140624648-ec736af7-f802-4b2a-884b-dce6bef35a75.mp4

### PR DESCRIPTION
**Pull request by yanurd**
## Description

Sets disabled to true if it hasn't been more than a day since the product was added to the list. This prevents user from clicking and overriding timestamp in database.

## Related Issue

Closes #27 

## Acceptance Criteria

> Sucede cuando tienes un producto marcado como "comprado" (checkbox como checked heavy_check_mark ), como usuario tienes todavía la posibilidad de "volver a marcar como comprado" un producto, sin importar si ya paso al menos un día y esto impacta/actualiza la base de datos. Lo cual no es un comportamiento esperado. Incluso, si realizas un check la primera vez, genera un error relacionado al input & custom input.

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|  ✓  | :bug: Bug fix              |
|   | :sparkles: New feature     |
|    | :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
|    | :scroll: Docs              |

## Testing Steps / QA Criteria

- `git fetch`
- `git pull origin fix-disable-checkbox`
- `git checkout`

### CODE REVIEW

File: src/components/show-products/index.js [hunk 1]
```diff
@@ -155,7 +155,8 @@ export const ShowProducts = () => {
                     id={id}
                     name={productName}
                     onChange={(event) => handleCheckboxChange(event, id)}
-                    checked={checked}
+                    checked={!!checked}
```
Comment (IsabellaSoares) [inline src/components/show-products/index.js:158]: Why they needed to change use `!!` on here?

**Review by IsabellaSoares — APPROVED** [review]
Thanks for fixing this issue, you did a great job guys! 🥳

As a suggestion for improving user feedback, I noticed that even when the checkbox is disabled, the cursor remains as "pointer" when we try to click on it. My suggestion is to add the `pointer-events` property when the checkbox is disabled to prevent this cursor "pointer" behavior. What do you think?

```
.checked-label {
  text-decoration: line-through;
  pointer-events: none;
}
```

File: src/components/show-products/index.js (hunk 1 above)
Comment (susird) [reply src/components/show-products/index.js:158]: It's because we have to fix the behavior of the input to controlled component using this operator to convert  undefined into truthy value
https://reactjs.org/docs/forms.html#controlled-components

Comment (IsabellaSoares) [reply src/components/show-products/index.js:158]: Wow! This is amazing! Thanks for the docs! ❤️

**Review by jandrade — APPROVED** [review]
Looks great! love the simplicity on this fix 👏 🚀!

File: src/components/show-products/index.js [hunk 2]
```diff
@@ -155,7 +155,8 @@ export const ShowProducts = () => {
...
+                    disabled={checked}
                     aria-label={TimeFrameLabels[timeFrameLabel]}
```
Comment (alxmcr) [inline src/components/show-products/index.js:160]: I like that you're using the `disabled` and `checked` properties. Now, it's clearer and simpler to understand. 💯 🎊

**Review by alxmcr — APPROVED** [review]
Approved ✔️ !

Well done. Thanks for your "fix" 😄 this small issue but very important 🙏 !

**Review by mailliwmogollon — APPROVED** [review]
good job...
