### PR TITLE
[Bug] Time frames radio group

### LINKED ISSUE #26: 14. Bug: Como usuario quiero adicionar un nuevo producto a mi lista, para así comenzar a registrar las compras.
Un artículo de la lista de compras se compone de los siguientes datos:

* Nombre del artículo
* ¿Qué tan pronto es probable que lo vuelva a comprar?
  * Pronto (en los próximos 7 días)
  * Más o menos pronto (en los próximos 14 días)
  * Más tarde (en los próximos 30 días)
* Última fecha de compra

Bug 🐞  :
Sucede cuando se desea crear un nuevo producto y ya se selecciono alguna de las opciones de frecuencia de compra (`soon`, `not-soon`, kind-of-soon), el radio button se "resetea" o siempre regresa al primer radio button. (ver video)

https://user-images.githubusercontent.com/8689897/140624351-1d3e94b4-149e-4026-b3b4-931c1304d0d6.mp4

Related issues: #4

### PR DESCRIPTION
**Pull request by IsabellaSoares**
_For an example of how to fill this template out, [see this Pull Request](https://github.com/the-collab-lab/tcl-3-smart-shopping-list/pull/44)._ 

## Description

Bug 🐞:
It happens when you want to create a new product and you have already selected one of the purchase frequency options (soon, not-soon, kind-of-soon), the radio button is "reset" or always returns to the first radio button.

This PR fixes the timeframe radio group bug, removes the unused component `RadioInput` and adds accessibility tags to menu buttons. The problem was with the custom radio button component. When interacting with the form the component got lost in the formState references. The solution was to use the native radio buttons.

## Related Issue

Closes #26 

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|  ✓ | :bug: Bug fix              |
|    | :sparkles: New feature     |
|  ✓ | :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
|    | :scroll: Docs              |

### Before

incorrect

### After

correct

## Testing Steps / QA Criteria

- From your terminal, pull down this branch with `git pull time-frame-bu` and check that branch out with `git checkout time-frame-bug`
- npm start to launch the app
- Fill in the "Shared token" field with the `isa-collection` token
- Access the add item screen and try to create a new product

### CODE REVIEW

File: src/components/add-form/index.js [hunk 1]
```diff
@@ -1,7 +1,12 @@
 import React from 'react';
-import RadioInput from '../radio-input';
 import './styles.css';
 
+const TimeFrames = {
+  soon: '7',
+  kindOfSoon: '14',
+  notSoon: '30',
+};
+
```
Comment (yanurd) [inline src/components/add-form/index.js:9]: Lol! i missed this when I created the new time frames, thaaaanks!!!

File: src/components/add-form/index.js [hunk 2]
```diff
@@ -18,38 +23,63 @@ const AddForm = ({ formState, handleForm }) => (
         required
       />
     </label>
-    <fieldset className="time-frame" defaultValue="7">
```
Comment (yanurd) [inline src/components/add-form/index.js:21]: This `defaultValue` was causing the bug? :eyes:

File: src/components/routing/Navigation/index.js [hunk 3]
```diff
@@ -24,12 +23,12 @@ function CustomLink({ children, to, disable }) {
 function Navigation() {
   return (
     <nav className="fixed navigation">
-      <CustomLink to="/list" aria-label="This button open your shopping list.">
+      <CustomLink to="/list" ariaLabel="This button open your shopping list.">
```
Comment (yanurd) [inline src/components/routing/Navigation/index.js:26]: Nice! thanks for the a11y!

File: src/components/add-form/styles.css [hunk 4]
```diff
@@ -36,22 +36,14 @@
...
-
 .time-frame-legend {
   text-align: center;
   font-size: 16px;
   font-weight: 700;
 }
 
-.time-frame-radio {
-  width: 30px;
+.time-frame-radio input {
```
Comment (yanurd) [inline src/components/add-form/styles.css:45]: Here, instead of giving the tag selector, if the input had the className given it would've worked too ^^

**Review by yanurd — APPROVED** [review]
Nice work :heart_eyes:

File: src/components/add-form/index.js (hunk 2 above)
Comment (IsabellaSoares) [reply src/components/add-form/index.js:21]: In fact, with the new way we check whether the field is checked or not (`checked={formState.timeFrame === TimeFrames.soon}`), this `defaultValue` has become unnecessary, as we have defined the default behavior in `defaultValues` on `AddItemPage`.

**Review by susird — APPROVED** [review]
The way you solved this bug is amazing, thanks for adding all the a11y to have more accessibility in our project. Well done! 👏 🔥

File: src/components/add-form/index.js [hunk 5]
```diff
@@ -18,38 +23,63 @@ const AddForm = ({ formState, handleForm }) => (
...
+          type="radio"
+          id="soon"
+          name="timeFrame"
+          value={TimeFrames.soon}
+          onChange={(event) => handleForm(event)}
+          checked={formState.timeFrame === TimeFrames.soon}
+        />
+        Soon
+      </label>
+      <br />
```
Comment (jandrade) [inline src/components/add-form/index.js:47]: Note that in this context, `<br />` is not semantic. I'd suggest using another approach to add a space between input elements.

One way could be adding a [gap](https://developer.mozilla.org/en-US/docs/Web/CSS/gap) value in the parent element, so each `label` can have its own padding (or gap). Up to you if you thing of a better approach for this :).

e.g.

```css
fieldset {
  ...
  gap: 16px;
}
```

According to W3C [^1] and MDN [^2], `<br />` should be used as line breaks inside content (e.g. inside `<p>something <br /> new line</p>`).

[^1]: https://www.w3.org/TR/2014/REC-html5-20141028/text-level-semantics.html#the-br-element.
[^2]: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/br

File: src/components/routing/Navigation/index.js (hunk 3 above)
Comment (jandrade) [reply src/components/routing/Navigation/index.js:26]: +++ 🎉

**Review by jandrade — APPROVED** [review]
LGTM, this is great! Thanks for fixing this issue and simplifying the implementation in the process :)

I just added a (non-blocking) minor comment, that can be done before merging.

Great job 🚢 🚀

File: src/components/add-form/index.js (hunk 1 above)
Comment (alxmcr) [reply src/components/add-form/index.js:9]: This object is so great and useful! 💯

File: src/components/routing/Navigation/index.js [hunk 6]
```diff
@@ -4,17 +4,16 @@ import { FiShoppingCart, FiPlus } from 'react-icons/fi';
 
 import './styles.css';
 
-function CustomLink({ children, to, disable }) {
+function CustomLink({ children, to, ariaLabel }) {
```
Comment (alxmcr) [inline src/components/routing/Navigation/index.js:7]: It's interesting that you've added an `ariaLabel` as a parameter! a11y is amazing! 💯 😄 

I'm so happy 😄  when I saw this:

image

Thank you 💛 !

File: src/components/routing/Navigation/index.js [hunk 7]
```diff
@@ -4,17 +4,16 @@ import { FiShoppingCart, FiPlus } from 'react-icons/fi';
...
     exact: true,
   });
   return (
     <Link
-      className={`navigation-link ${match ? 'selected' : ''} ${
-        disable ? 'disable-link' : ''
-      }`}
+      className={`navigation-link ${match ? 'selected' : ''}`}
       to={to}
+      aria-label={ariaLabel}
```
Comment (alxmcr) [inline src/components/routing/Navigation/index.js:16]: a11y is 💚 !

**Review by alxmcr — APPROVED** [review]
Approved ✔️ !

Well done! I really appreciate your taking care of a11y 💛 ! Of course, thank you for fixing the small bug. 😄

File: src/components/add-form/index.js (hunk 5 above)
Comment (IsabellaSoares) [reply src/components/add-form/index.js]: Hi @jandrade! Thank you very much for the suggestion! I didn't know this property, it will definitely help a lot! However, while making corrections I removed the tag and the styles remained the same. The `<br />` were unnecessary, apparently 😄
